steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" != "main" ]] && git rebase main || echo fail && true

    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    - name: python
      entrypoint: python
      args: ['-m', 'pip', 'install', '-r', 'requirements.txt', '--user']
    - name: python
      entrypoint: python
      args: ["-m", "pytest"]
    
    - name: 'node:20-bullseye'
      entrypoint: npm
      args: ["install"]
    - name: 'node:20-bullseye'
      entrypoint: npm
      args: ["run", "build"]

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'bash'
      args: ['-c', '[[ "$BRANCH_NAME" == "main" ]] && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy || echo fail && true']
      timeout: '1600s'
    
    - name: 'gcr.io/cloud-builders/gcloud'
      id: Connect to instance
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        mkdir -p ~/root/.ssh && \
        gcloud secrets versions access latest --secret=cloud-build-ssh-key > ~/root/.ssh/revm && \
        chmod 600 ~/root/.ssh/revm && \
        gcloud secrets versions access latest --secret=cloud-build-ssh-key-pub > ~/root/.ssh/revm.pub && \
        chmod 600 ~/root/.ssh/revm.pub && \
        set -x && \
        gcloud compute ssh revm --ssh-key-file=~/root/.ssh/revm --zone=us-central1-b && \
        gcloud compute ssh revm --zone=us-central1-b --ssh-key-file=~/root/.ssh/revm --command "ls"

options:
    logging: CLOUD_LOGGING_ONLY
