steps:
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    - name: python
      entrypoint: python
      args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']
options:
    logging: CLOUD_LOGGING_ONLY
    machineType: e2-standard-2
    region: us-central1
